<a href="https://colab.research.google.com/github/ppzovsky/estudo_py/blob/main/numpy/aula_de_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
lista = [1,2,3]

In [3]:
lista

[1, 2, 3]

In [4]:
np.array(lista)

array([1, 2, 3])

In [5]:
#a numpy e uma biblioteca de algebra linear, que tem o metodos compilado em C

In [6]:
matriz = [[1,2,3], [4,5,6],[7,8,9]]

In [7]:
matriz


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros ((4,7)) #cria uma matriz de zero

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones((5,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [12]:
np.eye(15) #cria matriz identidade

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [14]:
#o linspace parece o arange, mas ele n identifica o passo e sim a qtd de itens que o ussuario deseja

np.linspace(0,10,8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [17]:
np.random.rand(7)*50 #cria numeros aleatorios sem especificacao (dentro de parenteses e a qtd criada)

array([10.84761605,  0.71924492,  4.79542003, 48.99552043, 37.09221702,
       39.43141024, 22.49596224])

In [23]:
np.random.rand(5,4,3)*10 #cria matriz aleatoria

array([[[2.11985984, 7.92122882, 2.67716701],
        [7.33053224, 1.33972643, 6.98691697],
        [0.09390284, 2.05012601, 0.08834371],
        [8.73527287, 4.46818976, 4.82587882]],

       [[6.00623217, 3.7437496 , 6.45656347],
        [7.62868927, 4.55159508, 2.02063338],
        [7.98490114, 9.9412129 , 5.77070144],
        [8.52737851, 2.38510348, 8.57204469]],

       [[8.17847326, 9.17478086, 3.89567674],
        [7.26430774, 4.96284772, 0.47811091],
        [7.22108824, 6.92858297, 4.0129186 ],
        [1.70119346, 1.16956174, 9.02062606]],

       [[8.4765881 , 7.38103424, 7.46195706],
        [7.52908022, 6.17479137, 8.49970798],
        [2.66622815, 1.77878074, 2.23929168],
        [0.07534138, 5.90669947, 7.41916379]],

       [[8.01508099, 1.86797011, 7.13512856],
        [6.21601767, 0.45469004, 7.41226582],
        [7.15367077, 1.08010707, 2.37207699],
        [3.18334916, 7.42010548, 0.76417543]]])

In [22]:
np.random.randn(5,4,3)*10 #cria numeros aleatorio em uma distribuicao gaussiana

array([[[-18.30881951,  -3.62919977,  -1.25718114],
        [ -5.55156498,   1.45799535, -17.53104576],
        [  1.15388904,  -0.14952783,  -5.1949206 ],
        [-12.95866025,  -0.38936053,   6.47229362]],

       [[ -5.77226534,   6.12189672,   9.61284407],
        [ -0.50261783,  16.88865602,  -2.08634915],
        [-16.57847679,   4.7296205 ,  17.90502993],
        [-31.57632489,  24.85612257,   3.48287681]],

       [[ 19.23172202,  -2.93167697,   0.67818481],
        [  7.87908388, -10.10046391,  17.19051638],
        [ -2.96330568,   5.70475292,   0.56176674],
        [  8.74252906,  -1.42158365,  -5.24850536]],

       [[  1.51699272,  -0.52209613,  15.17121698],
        [ -7.38371066,   8.22034071,   6.76927709],
        [ -5.53551706,  -7.54049924,   2.18830087],
        [-10.92271667,   9.72161928, -11.44710818]],

       [[ -0.40499304,  -2.46759869,  -1.96816414],
        [-12.20750808,   1.09628095,  -2.03979304],
        [ -6.60473822,   1.6671302 ,  -5.95898527],
    

In [25]:
ex = np.random.randint(0,100,10) #cria nunmeross aleatorio inteiros

In [26]:
ex


array([66, 25, 75, 58, 64, 96, 20, 67, 56, 13])

In [28]:
ex.max() #mostra o maior elemento

96

In [29]:
ex.argmin() #mostra o indice do menor elemento

9