<a href="https://colab.research.google.com/github/ppzovsky/estudo_py/blob/main/numpy/Indexacao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import numpy as np

In [46]:
teste = np.arange(0,20,2)

In [47]:
teste

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
teste[4]

8

In [49]:
teste[:5] #destas formas conseguimos trazer sub arrays de arrays maiores

array([0, 2, 4, 6, 8])

In [50]:
teste[3:] = 25

In [11]:
teste

array([ 0,  2,  4, 25, 25, 25, 25, 25, 25, 25])

In [77]:
teste = np.arange(50).reshape(5,10)

In [78]:
teste

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [79]:
teste.shape

(5, 10)

In [80]:
teste2 = teste[:4].copy()

In [81]:
teste2[2:] = 5

In [82]:
teste2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5]])

In [83]:
teste #no python, estamos copiando no arra parea quem ele aponta, por isso, todas ass mudancas que aplicamoss no segundo array
#tambem altera o array principal
#para que isso nao acontece utilizamos o argumento copy

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [86]:
teste[1:3,5:] #antes da virgula pegamos as referencias das linhas que queremos e dpois das colunas

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [88]:
bol = teste > 10

In [89]:
teste[bol]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49])