<a href="https://colab.research.google.com/github/ppzovsky/estudo_py/blob/main/numpy/operacoes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
treino = np.random.randint(1,15,5)

In [4]:
treino

array([ 2, 11,  2,  4,  9])

In [5]:
treino + treino

array([ 4, 22,  4,  8, 18])

In [6]:
treino / treino

array([1., 1., 1., 1., 1.])

In [7]:
1 / treino

array([0.5       , 0.09090909, 0.5       , 0.25      , 0.11111111])

In [8]:
treino ** 2

array([  4, 121,   4,  16,  81])

In [9]:
treino + 2

array([ 4, 13,  4,  6, 11])

In [10]:
np.sqrt(treino)

array([1.41421356, 3.31662479, 1.41421356, 2.        , 3.        ])

In [11]:
np.exp(treino)

array([7.38905610e+00, 5.98741417e+04, 7.38905610e+00, 5.45981500e+01,
       8.10308393e+03])

In [12]:
np.mean(treino)

5.6

In [ ]:
#o mnumpy tem uma sserie de funcoes que podem sser vistas em ssua documentacao